### ISSUE TITLE
Run Eflux to obtain condition-specific fluxes based on proteomics

### ISSUE THREAD

**Issue by djinnome** [pnnl-predictive-phenomics/eflux#22]

**Comment by mcnaughtonadm** [comment]
Progress here

Eflux has been run on the proteomics data using the notebook provided in the `syn_bmca` repo to replicate how we did it with the transcriptomics.

Something of note(?). At the end of that notebook (after saving the file) the following lines of code are run:

```python

bounds = {r.name: r.dual for r in  condition_specific_models['D_T2_A'].constraints}
variables = {r.name: r.primal for r in condition_specific_models['D_T2_A'].variables if 'SLACK' in r.name}
variables
{v: x for v,x in variables.items() if (x!=0)}
```

Is the expected output of this an empty dict {} showing that all SLACK variables are 0 at the end?

I am getting the following:

```python
{'SLACK_MPOMC1': 1.4546932323173177e-16}
```
